import type { Word } from './types';

export const initialWordList: Word[] = [
  // EASY WORDS - Common everyday vocabulary
  { id: 1, nepali: "घर", roman: "Ghar", meaning_nepali: "बस्ने ठाउँ, निवास।", meaning_english: "House, home.", difficulty: 'easy' },
  { id: 2, nepali: "पानी", roman: "Pāni", meaning_nepali: "जल, उदक।", meaning_english: "Water.", difficulty: 'easy' },
  { id: 3, nepali: "खाना", roman: "Khānā", meaning_nepali: "भोजन, आहार।", meaning_english: "Food, meal.", difficulty: 'easy' },
  { id: 4, nepali: "काम", roman: "Kām", meaning_nepali: "कार्य, धन्दा।", meaning_english: "Work, job.", difficulty: 'easy' },
  { id: 5, nepali: "समय", roman: "Samaya", meaning_nepali: "समय, बेला।", meaning_english: "Time.", difficulty: 'easy' },
  { id: 6, nepali: "मान्छे", roman: "Mānche", meaning_nepali: "व्यक्ति, मानिस।", meaning_english: "Person, people.", difficulty: 'easy' },
  { id: 7, nepali: "राम्रो", roman: "Rāmro", meaning_nepali: "असल, उत्तम।", meaning_english: "Good, nice.", difficulty: 'easy' },
  { id: 8, nepali: "ठूलो", roman: "Ṭhūlo", meaning_nepali: "बड्डो, विशाल।", meaning_english: "Big, large.", difficulty: 'easy' },
  { id: 9, nepali: "सानो", roman: "Sāno", meaning_nepali: "सानो, साना।", meaning_english: "Small, little.", difficulty: 'easy' },
  { id: 10, nepali: "नयाँ", roman: "Nayāṃ", meaning_nepali: "नयाँ, नवीन।", meaning_english: "New.", difficulty: 'easy' },
  { id: 11, nepali: "पुरानो", roman: "Purāno", meaning_nepali: "पुरानो, प्राचीन।", meaning_english: "Old, ancient.", difficulty: 'easy' },
  { id: 12, nepali: "दिन", roman: "Din", meaning_nepali: "दिन, दिवस।", meaning_english: "Day.", difficulty: 'easy' },
  { id: 13, nepali: "रात", roman: "Rāt", meaning_nepali: "रात्री, निशा।", meaning_english: "Night.", difficulty: 'easy' },
  { id: 14, nepali: "आकाश", roman: "Ākāś", meaning_nepali: "आकाश, गगन।", meaning_english: "Sky.", difficulty: 'easy' },
  { id: 15, nepali: "पृथ्वी", roman: "Pṛthvī", meaning_nepali: "धरती, भूमि।", meaning_english: "Earth.", difficulty: 'easy' },
  { id: 16, nepali: "हावा", roman: "Hāvā", meaning_nepali: "वायु, बतास।", meaning_english: "Air, wind.", difficulty: 'easy' },
  { id: 17, nepali: "आगो", roman: "Āgo", meaning_nepali: "अग्नि, आगो।", meaning_english: "Fire.", difficulty: 'easy' },
  { id: 18, nepali: "रूख", roman: "Rūkh", meaning_nepali: "वृक्ष, बिरुवा।", meaning_english: "Tree.", difficulty: 'easy' },
  { id: 19, nepali: "फूल", roman: "Phūl", meaning_nepali: "पुष्प, फूल।", meaning_english: "Flower.", difficulty: 'easy' },
  { id: 20, nepali: "पैसा", roman: "Paisā", meaning_nepali: "धन, रुपैया।", meaning_english: "Money.", difficulty: 'easy' },

  // MEDIUM WORDS - Intermediate vocabulary  
  { id: 21, nepali: "शिक्षा", roman: "Śikṣā", meaning_nepali: "अध्ययन, विद्या।", meaning_english: "Education, learning.", difficulty: 'medium' },
  { id: 22, nepali: "स्वास्थ्य", roman: "Svāsthya", meaning_nepali: "निरोगी अवस्था, आरोग्य।", meaning_english: "Health.", difficulty: 'medium' },
  { id: 23, nepali: "परिवार", roman: "Parivār", meaning_nepali: "कुटुम्ब, घरको मान्छे।", meaning_english: "Family.", difficulty: 'medium' },
  { id: 24, nepali: "समाज", roman: "Samāj", meaning_nepali: "समुदाय, मानव समूह।", meaning_english: "Society, community.", difficulty: 'medium' },
  { id: 25, nepali: "संस्कृति", roman: "Saṃskṛti", meaning_nepali: "सभ्यता, परम्परा।", meaning_english: "Culture, tradition.", difficulty: 'medium' },
  { id: 26, nepali: "राजनीति", roman: "Rājanīti", meaning_nepali: "राज्य व्यवस्था, शासन कला।", meaning_english: "Politics, governance.", difficulty: 'medium' },
  { id: 27, nepali: "व्यापार", roman: "Vyāpār", meaning_nepali: "कारोबार, धन्दा।", meaning_english: "Business, trade.", difficulty: 'medium' },
  { id: 28, nepali: "प्रकृति", roman: "Prakṛti", meaning_nepali: "प्राकृतिक संसार, वातावरण।", meaning_english: "Nature, environment.", difficulty: 'medium' },
  { id: 29, nepali: "विज्ञान", roman: "Vijñān", meaning_nepali: "शास्त्रीय ज्ञान, साइन्स।", meaning_english: "Science.", difficulty: 'medium' },
  { id: 30, nepali: "प्रविधि", roman: "Pravidhi", meaning_nepali: "टेक्नोलोजी, तरिका।", meaning_english: "Technology, technique.", difficulty: 'medium' },
  { id: 31, nepali: "विकास", roman: "Vikās", meaning_nepali: "प्रगति, वृद्धि।", meaning_english: "Development, progress.", difficulty: 'medium' },
  { id: 32, nepali: "अनुभव", roman: "Anubhav", meaning_nepali: "अनुभूति, तजुर्बा।", meaning_english: "Experience.", difficulty: 'medium' },
  { id: 33, nepali: "योजना", roman: "Yojanā", meaning_nepali: "कार्यक्रम, प्लान।", meaning_english: "Plan, scheme.", difficulty: 'medium' },
  { id: 34, nepali: "समस्या", roman: "Samasyā", meaning_nepali: "कठिनाइ, चुनौती।", meaning_english: "Problem, challenge.", difficulty: 'medium' },
  { id: 35, nepali: "समाधान", roman: "Samādhān", meaning_nepali: "समस्याको हल, उपाय।", meaning_english: "Solution, remedy.", difficulty: 'medium' },
  { id: 36, nepali: "सम्मान", roman: "Sammān", meaning_nepali: "आदर, इज्जत।", meaning_english: "Respect, honor.", difficulty: 'medium' },
  { id: 37, nepali: "न्याय", roman: "Nyāya", meaning_nepali: "निष्पक्षता, ठीक इन्साफ।", meaning_english: "Justice, fairness.", difficulty: 'medium' },
  { id: 38, nepali: "शान्ति", roman: "Śānti", meaning_nepali: "चैन, सुख।", meaning_english: "Peace, tranquility.", difficulty: 'medium' },
  { id: 39, nepali: "सुरक्षा", roman: "Surakṣā", meaning_nepali: "रक्षा, बचाव।", meaning_english: "Security, protection.", difficulty: 'medium' },
  { id: 40, nepali: "स्वतन्त्रता", roman: "Svatantratā", meaning_nepali: "आजादी, मुक्ति।", meaning_english: "Freedom, independence.", difficulty: 'medium' },

  // DIFFICULT WORDS - Complex and advanced vocabulary
  { id: 41, nepali: "कण्ठ", roman: "Kaṇṭha", meaning_nepali: "घाँटी (विशेष गरी स्वर यन्त्र वा गाउन/पाठ गर्न प्रयोग हुने भाग), 'कण्ठले' वा 'कण्ठस्थ गरेको' अर्थमा पनि प्रयोग हुन्छ।", meaning_english: "Throat (specifically, the voice box or the part used for singing/recitation), also used to mean 'by heart' or 'memorized'.", difficulty: 'difficult' },
  { id: 42, nepali: "उद्विग्न", roman: "Udvigna", meaning_nepali: "चिन्तित, व्याकुल, उत्तेजित, व्यथित।", meaning_english: "Anxious, worried, agitated, distressed.", difficulty: 'difficult' },
  { id: 43, nepali: "सन्निपात", roman: "Sannipāt", meaning_nepali: "प्रलाप, रोगको गम्भीर अवस्था जहाँ विभिन्न शारीरिक रसहरू असन्तुलित हुन्छन् (आयुर्वेदिक परम्पराबाट), वा अचानक पतन।", meaning_english: "Delirium, a critical state of illness where multiple bodily humors are imbalanced (from Ayurvedic tradition), or a sudden collapse.", difficulty: 'difficult' },
  { id: 44, nepali: "परिपुर्ण", roman: "Paripurṇa", meaning_nepali: "पूर्ण, उत्तम, सन्तुष्ट, व्यापक।", meaning_english: "Complete, perfect, fulfilled, comprehensive.", difficulty: 'difficult' },
  { id: 45, nepali: "उपान्त", roman: "Upānta", meaning_nepali: "अन्तिमभन्दा अघिल्लो, अन्तिमबाट दोस्रो; साथै किनारा वा सिमाना।", meaning_english: "Penultimate, second to last; also edge or border.", difficulty: 'difficult' },
  { id: 46, nepali: "नैसर्गिक", roman: "Naisargik", meaning_nepali: "प्राकृतिक, सहज, जन्मजात।", meaning_english: "Natural, inherent, innate.", difficulty: 'difficult' },
  { id: 47, nepali: "अन्तर्निहित", roman: "Antarnihit", meaning_nepali: "अन्तर्निहित, निहित, भित्र रहेको, आधारभूत।", meaning_english: "Inherent, implicit, embedded, underlying.", difficulty: 'difficult' },
  { id: 48, nepali: "पौरुष", roman: "Pauruṣa", meaning_nepali: "पुरुषत्व, वीरता, शक्ति, वीर्य, प्रयास।", meaning_english: "Manliness, valor, strength, virility, effort.", difficulty: 'difficult' },
  { id: 49, nepali: "अभिप्राय", roman: "Abhiprāya", meaning_nepali: "मनसाय, उद्देश्य, विचार, अर्थ, लक्ष्य।", meaning_english: "Intention, purpose, opinion, meaning, aim.", difficulty: 'difficult' },
  { id: 50, nepali: "समीचीन", roman: "Samīcīna", meaning_nepali: "उपयुक्त, उचित, सही, तर्कसंगत, मिल्दो।", meaning_english: "Proper, appropriate, correct, reasonable, suitable.", difficulty: 'difficult' },
  { id: 51, nepali: "निष्कपट", roman: "Niṣkapaṭa", meaning_nepali: "निर्दोष, इमानदार, छलकपटरहित, स्पष्टवादी।", meaning_english: "Sincere, honest, guileless, frank.", difficulty: 'difficult' },
  { id: 52, nepali: "किंकर्तव्यविमूढ", roman: "Kiṃkartavyavimūḍha", meaning_nepali: "हतप्रभ, अलमल्ल परेको, के गर्ने के नगर्ने भनी रनभुल्ल परेको; दुविधामा परेको।", meaning_english: "Bewildered, perplexed, at a loss as to what to do; in a dilemma.", difficulty: 'difficult' },
  { id: 53, nepali: "अनावरत", roman: "Anāvarat", meaning_nepali: "निरन्तर, अविराम, नरोकिएको।", meaning_english: "Continuous, incessant, non-stop.", difficulty: 'difficult' },
  { id: 54, nepali: "मर्मस्पर्शी", roman: "Marmasparśī", meaning_nepali: "मर्मस्पर्शी, हृदयस्पर्शी, मन छुने।", meaning_english: "Touching, poignant, heart-touching.", difficulty: 'difficult' },
  { id: 55, nepali: "साहित्य", roman: "Sāhitya", meaning_nepali: "साहित्य, साहित्यिक कृतिहरू।", meaning_english: "Literature, literary works.", difficulty: 'difficult' },
  { id: 56, nepali: "अस्तित्व", roman: "Astitva", meaning_nepali: "अस्तित्व, सत्ता, हुनुको भाव।", meaning_english: "Existence, being.", difficulty: 'difficult' },
  { id: 57, nepali: "अभिव्यक्ति", roman: "Abhivyakti", meaning_nepali: "अभिव्यक्ति, प्रकटीकरण।", meaning_english: "Expression, manifestation.", difficulty: 'difficult' },
  { id: 58, nepali: "औचित्य", roman: "Auchitya", meaning_nepali: "उपयुक्तता, औचित्य, तर्कसंगतता, आधार।", meaning_english: "Propriety, appropriateness, justification, rationale.", difficulty: 'difficult' },
  { id: 59, nepali: "पारिभाषिक", roman: "Pāribhāṣik", meaning_nepali: "प्राविधिक, शब्दावलीसम्बन्धी, परिभाषासँग सम्बन्धित।", meaning_english: "Technical, terminological, pertaining to definition.", difficulty: 'difficult' },
  { id: 60, nepali: "यथार्थ", roman: "Yathārtha", meaning_nepali: "वास्तविकता, सत्य; यथार्थवादी।", meaning_english: "Reality, truth; realistic.", difficulty: 'difficult' },
]; 